name: Build and Release

on:
  push:
    branches:
      - plugin
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build plugin
        run: pnpm build:plugin

      - name: Zip extension folder
        run: |
          cd dist/extension
          zip -r ../../extension.zip .

      - name: Upload extension
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: extension.zip
